### ISSUE TITLE
window is not defined

### ISSUE THREAD

**Issue by abovethewater** [zingchart/ZingChart-React#3]
Just trying out ZingChart-React, but after a simple npm install I am seeing issues

    npm install zingchart-react --save

Lints fine, but then produces the following error (I am not even rendering the component at this point).

    ReferenceError: window is not defined
        at eval (eval at <anonymous> (/Users/jmathews/work/ops-tooling/node_modules/zingchart/client/zingchart.min.js:8:329), <anonymous>:1:1)
        at Object.<anonymous> (/Users/jmathews/work/ops-tooling/node_modules/zingchart/client/zingchart.min.js:8:1)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/jmathews/work/ops-tooling/node_modules/zingchart/index.js:1:1)
        at Module._compile (module.js:413:34)
        at Object.Module._extensions..js (module.js:422:10)
        at Module.load (module.js:357:32)
        at Function.Module._load (module.js:314:12)
        at Module.require (module.js:367:17)
        at require (internal/module.js:20:19)
        at Object.<anonymous> (/Users/jmathews/work/ops-tooling/node_modules/zingchart-react/dist/zingchart-react.min.js:1:215)

importing using Babel and ES6 syntax

    import { line as LineChart } from 'zingchart-react'

but doing a simpler import also produces the same error

    var ZingChart = require('zingchart-react').core;

npm package version 

    "zingchart-react": "^1.0.2"

Any pointers much appreciated.

**Comment by mike-schultz** [comment]
Are you calling the package directly from node? The library only works on the client side in a browser, which is most likely the cause of the error  `window is not defined`.

**Comment by abovethewater** [comment]
Thanks for the quick response.
That'll be the issue.

I'm using [React Starter Kit](https://github.com/kriasoft/react-starter-kit), building out a prototype, trying React as I go, and wanted to include this lib.

It is ultimately for use in the browser, but RSK does server side rendering too (It's a hell of a rabbit hole..), and the simple act of requiring / importing the module triggers the bind to window.

Moving the require into the function (can't use import) gets it past this point, but running into further issues.

For now I can generate the chart using your boilerplate repo and include it as a simple image, but would be great to have an out of the box solution that I can import using ES6 syntax, and simply include.

I may come back to this once I understand the whole ecosystem a bit better, but for now I'll close this as "not a bug".
